### ISSUE TITLE
「カテゴリーを選択」のドロップダウンメニューをスクロールできるようにしてほしい

### ISSUE THREAD

**Issue by gaaamii** [nakazye/ProgrammerProfile#19]
こんなかんじにして欲しいです
![](http://i.gyazo.com/1172c7786a91376fd626c012367ca2b6.gif)

``` css
/* 対象の要素に */
height: 400px;
overflow: scroll;
```

みたいな感じになると思います。

**Comment by nakazye** [comment]
ソースまで！ありがとうございます！仕事終えて帰ったら対応します！

**Comment by gaaamii** [comment]
お仕事中にすみません！プルリク送った方がいいかなとも思ったんですが、改修要望はIssuesとTwitterと書いてあったので。

応援してます！運営頑張ってください！ :+1:

**Comment by nakazye** [comment]
ありがとうございます！ソースがクソきたない（自前のcssファイルやjsファイルが無い）ので、こうご指摘いただけると本当に助かります！
がんばります！
