### ISSUE TITLE
カテゴリに「構成管理ツール」を追加していただきたい

### ISSUE THREAD

**Issue by nagi2100** [nakazye/ProgrammerProfile#20]
構成管理ツールカテゴリを新設し、以下を追加いただきたいです。
・Puppet
・Chef
・Ansible

**Comment by nakazye** [comment]
インフラとしてしまうと漠然としすぎちゃうなーと、そのあたり悩んでた部分です！構成管理ツールってカテゴリだといい感じですね。追加します（ただ、今日は残業あったので手が回るか微妙です・・・）
