### ISSUE TITLE
フォローすべき人たちのページに追加用ID検索窓が欲しい

### ISSUE THREAD

**Issue by roiti46** [nakazye/ProgrammerProfile#24]
あの人が推薦されてないときに、いちいちホームに戻る手間があるので、
各分野のフォローすべき人たちのページに追加用検索窓を追加してほしいです。

**Comment by nakazye** [comment]
割とすぐ反映できそうで有益な提案ありがとうございます！盛り込む方針でいきます！

**Comment by nakazye** [comment]
closeの番号間違えました・・・言語等選択後、窓が表示されるようになりました
