### ISSUE TITLE
「※ %表示は、一番を多い分野を100%とした際の割合です。」の日本語がおかしい。

### ISSUE THREAD

**Issue by rbtnn** [nakazye/ProgrammerProfile#25]
> http://www.programmerprofile.net/stats/

このページの「※ %表示は、一番を多い分野を100%とした際の割合です。」は、
「一番を多い分野」ではなく「一番多い分野」ではないでしょうか。
簡単ではありますが、発見したので報告します。よろしくお願い致します。

**Comment by nakazye** [comment]
ありがとうございます！指摘頂けなければずっと恥ずかしい思いするところでした。修正しますー
